import NavBar from '@/components/NavBar'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Protected',
  description: 'Generated by create next app',
}

export default function ProtectedLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <section>
      <NavBar />
      {children}
    </section>
  )
}
